server:
  port: 8888

spring:
  application:
    name: baseic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blog

  redis:
    url: 192.168.56.102
    port: 7000
    database: 0

  thymeleaf:
    encoding: UTF-8
    cache: true


